### ISSUE TITLE
 critical Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

### ISSUE THREAD

**Issue by thisVioletHydra** [zeokku/vite-plugin-vue-static-css-modules#10]
![image](https://github.com/zeokku/vite-plugin-vue-css-modules/assets/11839238/ff0d3a0d-e103-4d78-beff-6bf398653aef)
 More info           │ https://github.com/advisories/GHSA-67hx-6x53-jw92

**Comment by Lutymane** [comment]
Should be fixed now
